# Generated by Django 3.2 on 2021-04-15 10:02

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_movieimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(upload_to=mainapp.models.movie_directory_path_with_uuid),
        ),
    ]
